config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get '/readings', to: 'readings#index'
  # post '/readings', to: 'readings#create'
  # get '/readings/new', to: 'readings#new', as: 'new_page_page'
  # get '/readings/:id', to: 'readings#show', as: 'page'
  # get '/readings/:id/edit', to: 'readings#edit', as: 'edit_page'
  # patch '/readings/:id', to: 'readings#update'
  # delete '/readings/:id', to: 'readings#destroy'

  resources :readings do
    resources :samples
  end
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, :controllers => { registrations: 'registrations' }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'home/index'

  get 'home/login'

  root to: "readings#index"
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], user: {except: [:destroy]}, site_admin: :all
  layout "sample"

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
    @page_title = "Sample History Overview"
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @reading = Reading.find(params[:reading_id])
    @sample_gp_1 = Sample.where(sample_id: params[:reading_id], :sample_gp => 1 )
    @sample_gp_2 = Sample.where(sample_id: params[:reading_id], :sample_gp => 2 )
    @sample_gp_3 = Sample.where(sample_id: params[:reading_id], :sample_gp => 3 )
    @sample_gp_4 = Sample.where(sample_id: params[:reading_id], :sample_gp => 4 )
    @page_title = "Input sample data"

    @sample = @reading.samples.build
    label_1 = 0
    @reading_number_label_1 = label_1 + 1

    label_2 = 0
    @reading_number_label_2 = label_2 + 1

    # Nematodes (Bacteria) (Samples 1-4) Cell B41
    @nematodes_bacteria_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_bacteria).last
    @nematodes_bacteria_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_bacteria).last
    @nematodes_bacteria_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_bacteria).last
    @nematodes_bacteria_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_bacteria).last 

    # Nematodes (Fungal) (Samples 1-4) Cell C41
    @nematodes_fungi_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_fungi).last
    @nematodes_fungi_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_fungi).last
    @nematodes_fungi_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_fungi).last
    @nematodes_fungi_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_fungi).last

    # Nematodes (Root) (Samples 1-4) Cell E41
    @nematodes_root_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_root).last
    @nematodes_root_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_root).last
    @nematodes_root_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_root).last
    @nematodes_root_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_root).last

    # Nematodes (Predator) (Samples 1-4) Cell D41
    @nematodes_predator_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_predator).last
    @nematodes_predator_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_predator).last
    @nematodes_predator_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_predator).last
    @nematodes_predator_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_predator).last

    # Nematodes (Dilution) (Samples 1-4) Cell D41
    @nematodes_dilution_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_dilution).last
    @nematodes_dilution_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_dilution).last
    @nematodes_dilution_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_dilution).last
    @nematodes_dilution_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_dilution).last

    # Notes (Samples 1-4)
    @notes_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:notes).last
    @notes_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:notes).last
    @notes_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:notes).last
    @notes_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:notes).last
  end

  # GET /samples/new
  def new
    # this is temporary until it works then we can put it in the route - this is probably the edit view
    @reading = Reading.find(params[:reading_id])

    @sample_gp_1 = Sample.where(sample_id: params[:reading_id], :sample_gp => 1 )
    @sample_gp_2 = Sample.where(sample_id: params[:reading_id], :sample_gp => 2 )
    @sample_gp_3 = Sample.where(sample_id: params[:reading_id], :sample_gp => 3 )
    @sample_gp_4 = Sample.where(sample_id: params[:reading_id], :sample_gp => 4 )

    # Nematodes (Bacteria) (Samples 1-4) Cell B41
    @nematodes_bacteria_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_bacteria).last
    @nematodes_bacteria_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_bacteria).last
    @nematodes_bacteria_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_bacteria).last
    @nematodes_bacteria_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_bacteria).last 

    # Nematodes (Fungal) (Samples 1-4) Cell C41
    @nematodes_fungi_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_fungi).last
    @nematodes_fungi_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_fungi).last
    @nematodes_fungi_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_fungi).last
    @nematodes_fungi_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_fungi).last

    # Nematodes (Root) (Samples 1-4) Cell E41
    @nematodes_root_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_root).last
    @nematodes_root_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_root).last
    @nematodes_root_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_root).last
    @nematodes_root_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_root).last

    # Nematodes (Predator) (Samples 1-4) Cell D41
    @nematodes_predator_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_predator).last
    @nematodes_predator_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_predator).last
    @nematodes_predator_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_predator).last
    @nematodes_predator_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_predator).last

    # Nematodes (Dilution) (Samples 1-4) Cell D41
    @nematodes_dilution_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_dilution).last
    @nematodes_dilution_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_dilution).last
    @nematodes_dilution_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_dilution).last
    @nematodes_dilution_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_dilution).last

    # Notes (Samples 1-4)
    @notes_last_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:notes).last
    @notes_last_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:notes).last
    @notes_last_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:notes).last
    @notes_last_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:notes).last

    # get existing readings from database   
    @samples = Sample.where(sample_id: params[:reading_id]).to_a

    # add new item to array for next reading number if < 20
    @sample = @reading.samples.new
    @sample.reading_number = @samples.length + 1

    @page_title = "Input Sample Data"
  end

  # GET /samples/1/edit
  def edit

  end

  # POST /samples
  # POST /samples.json
  def create
    @reading = Reading.find(params[:reading_id])
    
    # @reading = Reading.samples.new(sample_params)
    @samples = Sample.where(sample_id: params[:reading_id]).to_a

    @sample = @reading.samples.new(sample_params)
    @sample.sample_id = params[:reading_id]
    @sample.reading_number = @samples.length + 1

    # respond_to do |format|
    #   puts "-----------------------"
    #   puts "sample_params = "
    #   sample_params.each do |k, v|
    #     puts(k)
    #     puts(v)
    #   end
    #   puts "-----------------------"

    respond_to do |format|
      if @sample.save
        format.html { redirect_to new_reading_sample_path, notice: 'Sample was successfully created.' }
      else
        redirect_to new_reading_sample_path, notice: 'An error occured. Try submitting your record again.'
      end
    end

    puts 'params = '
    puts params.inspect
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      # @sample = Sample.find(params[:id])
      @sample = Sample.where(sample_id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(
        :sample_id, 
        :sample_gp, 
        :bacterial_number, 
        :bacterial_size_shape, 
        :bacterial_mean, 
        :bacterial_standard_deviation, 
        :bacterial_dilution, 
        :no_bacteria_per_gram, 
        :micrograms, 
        :actinobacteria, 
        :actinobacteria_mean, 
        :actinobacterial_standard_deviation, 
        :actinobacteria_dilution, 
        :actinobacteria_dilution, 
        :actinobacteria_length_cm, 

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_reading_header.html.erb
<div class="container reading-header">

  <div class="row">

    <div class="col-md-12">

      <h5>Location Entry</h5>

    <div class="reading-header-container">
      <table class="reading-header">
        <thead>
          <tr>
            <th>Client</th>
            <th>Organisation</th>
            <th>Date collected</th>
            <th>Date observed</th>
            <th>Location</th>
            <th>Sample Type</th>
            <th>Plants present</th>
            <th>Plants desired</th>
            <th>LT ID</th>
            <th>Customer ID</th>
            <th>Other notes</th>
            <th>Observed by</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
            <tr>
              <td><%= @reading.client %></td>
              <td><%= @reading.organisation %></td>
              <td><%= @reading.date_collected %></td>
              <td><%= @reading.date_observed %></td>
              <td><%= @reading.location %></td>
              <td><%= @reading.sample_type %></td>
              <td><%= @reading.plants_present %></td>
              <td><%= @reading.plants_desired %></td>
              <td><%= @reading.lt_id %></td>
              <td><%= @reading.cust_id %></td>
              <td><%= @reading.other_notes %></td>
              <td><%= @reading.observed_by %></td>
              <td><%= link_to 'Edit', edit_reading_path(@reading) %></td>
              <td><%= link_to 'Back', readings_path  %></td>
            </tr>
        </tbody>
      </table>

    </div>
    
    </div>

  </div>

</div>

app/views/samples/edit.html.erb
<h1>Update your sample here</h1>

<%= render 'reading_header', reading: @reading %>

<%= render 'form', sample: @sample %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<div class="container">

  <header>
    <h1>Samples</h1>
    <h2>Log History</h2>
  </header>

  <main>
    
    <div class="container">
      <div class"sample-notice">
        <p id="notice"><%= notice %></p>
      </div>
    </div>

    <div class="container">
      <div class="flex-centre"
        <div class="sample-history-item"><%= link_to 'New Sample', new_reading_sample_path %></div>
      </div>
    </div>

    <% if @samples.blank? %>
      <div class="container centre-text">
        <h3>No sample records have been uploaded. Please upload the first sample below...</h3>
      </div>
    <% else %>
      <% @samples.each do |sample| %>

        <div class="container">

          <!-- Header -->
          <div class="sample-history flex-wrap sample-summary">

            <div class="sample-history-inner">

              <div class="sample-history-item">
                <h3>User ID:</h3>
                <p><%= sample.user_id %></p>
              </div>

              <div class="sample-history-item">
                <h3>Sample ID:</h3>
                <p><%= sample.sample_id %></p>
              </div>

              <div class="sample-history-item">
                <h3>Reading Number:</h3>
                <p><%= sample.reading_number %></p>
              </div>
              
            </div>

            <div class="sample-history-inner">
              <div class="sample-history-item">
                <h3>Date taken:</h3>
                <p><%= sample.sample_date %></p>
              </div>

              <div class="sample-history-item">
                <h3>GPS Location of Sample:</h3>
                <p><%= sample.gps %></p>
              </div>

            </div> <!-- End of sample-history-inner div -->

            <!-- This is where the old code was originally -->

            <!-- CRUD Options -->
            <div class="sample-history-inner crud-options">
              <div class="sample-history-item"><%= link_to 'View Record', sample %></div>
              <div class="sample-history-item"><%= link_to 'Edit Record', edit_sample_path(sample) if logged_in?(:site_admin) %></div>
              <div class="sample-history-item"><%= link_to 'Delete Record', sample, method: :delete, data: { confirm: 'Are you sure?' }  if logged_in?(:site_admin) %></div>
            </div> <!-- End of CRUD div -->

          </div> <!-- End of sample-history div -->
          
        </div> <!-- End of container div -->

      <% end %> <!-- End of sample loop -->
    
    <% end %> <!-- End of if statement -->
    
  </main>

</div>

app/views/samples/new.html.erb
<div class="container centre-text">

    <h3>Sample Data</h3>

</div class>

<div class="container">

  <div class="d-flex justify-content-start">

    <% if current_user.is_a?(GuestUser) %>

          <div class="p-2 login-top-inner">
            <%= link_to "Register", new_user_registration_path %>
          </div>
          <div class="p-2 login-top-inner">
            <%= link_to "Login", new_user_session_path %>
          </div>

    <% else %>

          <div class="p-2 login-top-inner">
            <%= link_to "Home", root_path %>
          </div>
          <div class="p-2 login-top-inner">
            <%= link_to "Your Account", edit_user_registration_path %>
          </div>
          <div class="p-2 login-top-inner">
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </div>

    <% end %>

        <div class="p-2 ml-auto greeting">
          <h5>Hello, <%= current_user.first_name %></h5>
          <p id="notice"><%= notice %></p>
        </div>

  </div>

</div>

<%= render 'reading_header', reading: @reading %>

<%= render 'form', 
    sample_gp_1: @sample_gp_1, 
    sample_gp_2: @sample_gp_2, 
    sample_gp_3: @sample_gp_3, 
    sample_gp_4: @sample_gp_4, 
    nematodes_bacteria_last_1: @nematodes_bacteria_last_1, 
    nematodes_bacteria_last_2: @nematodes_bacteria_last_2, 
    nematodes_bacteria_last_3: @nematodes_bacteria_last_3, 
    nematodes_bacteria_last_4: @nematodes_bacteria_last_4, 
    nematodes_fungi_last_1: @nematodes_fungi_last_1, 
    nematodes_fungi_last_2: @nematodes_fungi_last_2, 
    nematodes_fungi_last_3: @nematodes_fungi_last_3, 
    nematodes_fungi_last_4: @nematodes_fungi_last_4, 
    nematodes_root_last_1: @nematodes_root_last_1, 
    nematodes_root_last_2: @nematodes_root_last_2, 
    nematodes_root_last_3: @nematodes_root_last_3, 
    nematodes_root_last_4: @nematodes_root_last_4, 
    nematodes_predator_last_1: @nematodes_predator_last_1, 
    nematodes_predator_last_2: @nematodes_predator_last_2, 
    nematodes_predator_last_3: @nematodes_predator_last_3, 
    nematodes_predator_last_4: @nematodes_predator_last_4, 
    nematodes_dilution_last_1: @nematodes_dilution_last_1, 
    nematodes_dilution_last_2: @nematodes_dilution_last_2, 
    nematodes_dilution_last_3: @nematodes_dilution_last_3, 
    nematodes_dilution_last_4: @nematodes_dilution_last_4, 
    notes_last_1: @notes_last_1, 
    notes_last_2: @notes_last_2, 
    notes_last_3: @notes_last_3, 
    notes_last_4: @notes_last_4, 
    reading: @reading,
    sample: @sample, 
    entry_1_label: @entry_1_label, 
    entry_2_label: @entry_2_label, 
    entry_3_label: @entry_3_label, 
    entry_4_label: @entry_4_label 
     %>

app/views/samples/show.html.erb
<div class="container centre-text">

    <h3>Sample Data</h3>

</div class>

<div class="container">

  <div class="d-flex justify-content-start">

    <% if current_user.is_a?(GuestUser) %>

          <div class="p-2 login-top-inner">
            <%= link_to "Register", new_user_registration_path %>
          </div>
          <div class="p-2 login-top-inner">
            <%= link_to "Login", new_user_session_path %>
          </div>

    <% else %>

          <div class="p-2 login-top-inner">
            <%= link_to "Home", root_path %>
          </div>
          <div class="p-2 login-top-inner">
            <%= link_to "Your Account", edit_user_registration_path %>
          </div>
          <div class="p-2 login-top-inner">
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </div>

    <% end %>

        <div class="p-2 ml-auto greeting">
          <h5>Hello, <%= current_user.first_name %></h5>
          <p id="notice"><%= notice %></p>
        </div>

  </div>

</div>

<%= render 'reading_header', reading: @reading %>

<%= render 'form', 
    sample_gp_1: @sample_gp_1, 
    sample_gp_2: @sample_gp_2, 
    sample_gp_3: @sample_gp_3, 
    sample_gp_4: @sample_gp_4, 
    nematodes_bacteria_last_1: @nematodes_bacteria_last_1, 
    nematodes_bacteria_last_2: @nematodes_bacteria_last_2, 
    nematodes_bacteria_last_3: @nematodes_bacteria_last_3, 
    nematodes_bacteria_last_4: @nematodes_bacteria_last_4, 
    nematodes_fungi_last_1: @nematodes_fungi_last_1, 
    nematodes_fungi_last_2: @nematodes_fungi_last_2, 
    nematodes_fungi_last_3: @nematodes_fungi_last_3, 
    nematodes_fungi_last_4: @nematodes_fungi_last_4, 
    nematodes_root_last_1: @nematodes_root_last_1, 
    nematodes_root_last_2: @nematodes_root_last_2, 
    nematodes_root_last_3: @nematodes_root_last_3, 
    nematodes_root_last_4: @nematodes_root_last_4, 
    nematodes_predator_last_1: @nematodes_predator_last_1, 
    nematodes_predator_last_2: @nematodes_predator_last_2, 
    nematodes_predator_last_3: @nematodes_predator_last_3, 
    nematodes_predator_last_4: @nematodes_predator_last_4, 
    nematodes_dilution_last_1: @nematodes_dilution_last_1, 
    nematodes_dilution_last_2: @nematodes_dilution_last_2, 
    nematodes_dilution_last_3: @nematodes_dilution_last_3, 
    nematodes_dilution_last_4: @nematodes_dilution_last_4, 
    notes_last_1: @notes_last_1, 
    notes_last_2: @notes_last_2, 
    notes_last_3: @notes_last_3, 
    notes_last_4: @notes_last_4, 
    reading: @reading,
    sample: @sample, 
    entry_1_label: @entry_1_label, 
    entry_2_label: @entry_2_label, 
    entry_3_label: @entry_3_label, 
    entry_4_label: @entry_4_label %>