config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get '/readings', to: 'readings#index'
  # post '/readings', to: 'readings#create'
  # get '/readings/new', to: 'readings#new', as: 'new_page_page'
  # get '/readings/:id', to: 'readings#show', as: 'page'
  # get '/readings/:id/edit', to: 'readings#edit', as: 'edit_page'
  # patch '/readings/:id', to: 'readings#update'
  # delete '/readings/:id', to: 'readings#destroy'

  resources :readings do
    resources :samples
  end
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, :controllers => { registrations: 'registrations' }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'home/index'

  get 'home/login'

  root to: "readings#index"
end

app/models/reading.rb
class Reading < ApplicationRecord
    belongs_to :user

    has_many :samples, dependent: :destroy

    validates_presence_of :client, :organisation, :location, :plants_present, :plants_desired

    accepts_nested_attributes_for :samples, allow_destroy: true;

    def to_s
        client
    end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_action :set_reading, :set_user, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /readings
  def index
    @readings = Reading.all
    @user_readings = current_user.readings
  end

  # GET /readings/1
  def show
#   @samples = @reading.samples

    @samples = Sample.where(sample_id: params[:id])

    # Report - Bacterial Micrograms (Samples 1-4) Cell Z13
    @bacterial_microgram_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:micrograms).last
    @bacterial_microgram_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:micrograms).last
    @bacterial_microgram_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:micrograms).last
    @bacterial_microgram_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:micrograms).last

    # Report - Actinobacteria Micrograms (Samples 1-4) Cell Z18
    @actinobacterial_microgram_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:actinobacteria_micrograms).last
    @actinobacterial_microgram_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:actinobacteria_micrograms).last
    @actinobacterial_microgram_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:actinobacteria_micrograms).last
    @actinobacterial_microgram_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:actinobacteria_micrograms).last

    # Report - Fungi Micrograms (Samples 1-4) Cell Z21
    @fungi_microgram_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:fungi_micrograms).last
    @fungi_microgram_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:fungi_micrograms).last
    @fungi_microgram_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:fungi_micrograms).last
    @fungi_microgram_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:fungi_micrograms).last

    # Report - Oomycetes Micrograms (Samples 1-4) Cell Z28
    @oomycetes_microgram_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:oomycetes_micrograms).last
    @oomycetes_microgram_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:oomycetes_micrograms).last
    @oomycetes_microgram_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:oomycetes_micrograms).last
    @oomycetes_microgram_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:oomycetes_micrograms).last

    # Report - Flagellate (Protozoa) (Samples 1-4) Cell Y35
    @flagellate_protozoa_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:flagellate_protozoa).last
    @flagellate_protozoa_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:flagellate_protozoa).last
    @flagellate_protozoa_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:flagellate_protozoa).last
    @flagellate_protozoa_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:flagellate_protozoa).last

    # Report - Amoebae (Protozoa) (Samples 1-4) Cell Y36
    @amoebae_protozoa_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:amoebae_protozoa).last
    @amoebae_protozoa_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:amoebae_protozoa).last
    @amoebae_protozoa_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:amoebae_protozoa).last
    @amoebae_protozoa_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:amoebae_protozoa).last 

    # Report - Ciliates (Protozoa) (Samples 1-4) Cell Y37
    @ciliates_protozoa_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:ciliates_protozoa).last
    @ciliates_protozoa_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:ciliates_protozoa).last
    @ciliates_protozoa_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:ciliates_protozoa).last
    @ciliates_protozoa_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:ciliates_protozoa).last 

    # Report - Nematodes (Bacteria) (Samples 1-4) Cell B41
    @nematodes_bacteria_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_bacteria).last
    @nematodes_bacteria_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_bacteria).last
    @nematodes_bacteria_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_bacteria).last
    @nematodes_bacteria_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_bacteria).last 

    # Report - Nematodes (Fungal) (Samples 1-4) Cell C41
    @nematodes_fungi_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_fungi).last
    @nematodes_fungi_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_fungi).last
    @nematodes_fungi_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_fungi).last
    @nematodes_fungi_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_fungi).last

    # Report - Nematodes (Root) (Samples 1-4) Cell E41
    @nematodes_root_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_root).last
    @nematodes_root_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_root).last
    @nematodes_root_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_root).last
    @nematodes_root_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_root).last

    # Report - Nematodes (Predator) (Samples 1-4) Cell D41
    @nematodes_predator_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_predator).last
    @nematodes_predator_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_predator).last
    @nematodes_predator_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_predator).last
    @nematodes_predator_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_predator).last

    # Report - Nematodes (Total) (Samples 1-4) Cell V41
    @nematodes_total_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:nematodes_mean).last
    @nematodes_total_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:nematodes_mean).last
    @nematodes_total_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:nematodes_mean).last
    @nematodes_total_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:nematodes_mean).last

    # Report - FB Biomass (Samples 1-4) Cell Z36
    @fb_biomass_ratio_report_1 = Sample.where(id: @reading.samples, sample_gp: 1).pluck(:fb_biomass_ratio).last
    @fb_biomass_ratio_report_2 = Sample.where(id: @reading.samples, sample_gp: 2).pluck(:fb_biomass_ratio).last
    @fb_biomass_ratio_report_3 = Sample.where(id: @reading.samples, sample_gp: 3).pluck(:fb_biomass_ratio).last
    @fb_biomass_ratio_report_4 = Sample.where(id: @reading.samples, sample_gp: 4).pluck(:fb_biomass_ratio).last
  end

  # GET /readings/new
  def new
    @reading = Reading.new
  end

  # GET /readings/1/edit
  def edit
  end

  # POST /readings
  def create
    @reading = Reading.new(reading_params)
    @reading.user = current_user

    if @reading.save
      redirect_to @reading, notice: 'Reading was successfully created.'
    else
      render :new, notice: 'An error occured. Try submitting your record again.'
    end
  end

  # PATCH/PUT /readings/1
  def update
    if @reading.update(reading_params)
      redirect_to @reading, notice: 'Reading was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /readings/1
  def destroy
    @reading.destroy
    redirect_to readings_url, notice: 'Reading was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading
      @reading = Reading.find(params[:id])
      @sample = Sample.where(sample_id: params[:id])
    end

    def set_user
      @user_id = current_user.id
    end

    # Only allow a trusted parameter "white list" through.
    def reading_params
      params.require(:reading).permit(:client, :organisation, :date_collected, :date_observed, :location, :plants_present, :plants_desired, :other_notes, :observed_by, :lt_id, :cust_id, :user_id, :sample_type)
    end
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/_form.html.erb
<%= form_for(reading) do |f| %>
  <% if reading.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(reading.errors.count, "error") %> prohibited this reading from being saved:</h3>

      <ul>
      <% reading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="reading-input">
    <tr>
      <th><%= f.label :client %></th>
      <td class="cfp-field"><%= f.text_field :client %></td>
    </tr>
    <tr>
      <th><%= f.label :organisation %></th>
      <td class="cfp-field"><%= f.text_field :organisation %></td>
    </tr>
    <tr>
      <th><%= f.label :date_collected %></th>
      <td class="cfp-field"><%= f.datetime_select :date_collected %></td>
    </tr>
    <tr>
      <th><%= f.label :date_observed %></th>
      <td class="cfp-field"><%= f.datetime_select :date_observed %></td>
    </tr>
    <tr>
      <th><%= f.label :location %></th>
      <td class="cfp-field"><%= f.text_field :location %></td>
    </tr>
    <tr>
      <th><%= f.label :sample_type %></th>
      <td class="cfp-field"><%= sample_type_choice = ["Field", "Compost"] 
      f.select :sample_type, sample_type_choice %></td>
    </tr>    
    <tr>
      <th><%= f.label :plants_present %></th>
      <td class="cfp-field"><%= f.text_field :plants_present %></td>
    </tr>
    <tr>
      <th><%= f.label :plants_desired %></th>
      <td class="cfp-field"><%= f.text_field :plants_desired %></td>
    </tr>
    <tr>
      <th><%= f.label :other_notes %></th>
      <td class="cfp-field"><%= f.text_area :other_notes %></td>
    </tr>
    <tr>
      <th><%= f.label :observed_by %></th>
      <td class="cfp-field"><%= f.text_field :observed_by %></td>
    </tr>
    <tr>
      <th><%= f.label "LT Id:" %></th>
      <td class="cfp-field"><%= f.number_field :lt_id %></td>
    </tr>
    <tr>
      <th><%= f.label "Cust Id:" %></th>
      <td class="cfp-field"><%= f.number_field :cust_id %></td>
    </tr>
    <tr>
      <th colspan="2"><%= f.submit "Submit", class: "btn btn-success" %></th>
    </tr>
  </table>

<% end %>

app/views/readings/_new_reading.html.erb
<h3>New Reading</h3>

<%= form_for(reading) do |f| %>
  <% if reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% reading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>

  <div class="reading-input-field">
    <%= f.label :client %>
    <%= f.text_field :client %>
  </div>

  <div class="reading-input-field">
    <%= f.label :organisation %>
    <%= f.text_field :organisation %>
  </div>

  <div class="reading-input-field">
    <%= f.label :date_collected %>
    <%= f.datetime_select :date_collected %>
  </div>

  <div class="reading-input-field">
    <%= f.label :date_observed %>
    <%= f.datetime_select :date_observed %>
  </div>

  <div class="reading-input-field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="reading-input-field">
    <%= f.label :plants_present %>
    <%= f.text_field :plants_present %>
  </div>

  <div class="reading-input-field">
    <%= f.label :plants_desired %>
    <%= f.text_field :plants_desired %>
  </div>

  <div class="reading-input-field">
    <%= f.label :other_notes %>
    <%= f.text_area :other_notes %>
  </div>

  <div class="reading-input-field">
    <%= f.label :observed_by %>
    <%= f.text_field :observed_by %>
  </div>

  <div class="reading-input-field">
    <%= f.label :lt_id %>
    <%= f.number_field :lt_id %>
  </div>

  <div class="reading-input-field">
    <%= f.label :cust_id %>
    <%= f.number_field :cust_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readings/_reading_list.html.erb
<h3>Location History</h3>

<% if readings.present? %>

<p class="centre-text">Your location records are shown below. Click on a location to edit its details or add sample data.</p>

  <table class="reading-header">
    <thead>
      <tr>
        <th>Client</th>
        <th>Organisation</th>
        <th>Date collected</th>
        <th>Date observed</th>
        <th>Location</th>
        <th>Plants present</th>
        <th>Plants desired</th>
        <th>Other notes</th>
        <th>Observed by</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% readings.each do |reading| %>
        <tr>
          <td><%= reading.client %></td>
          <td><%= reading.organisation %></td>
          <td><%= reading.date_collected %></td>
          <td><%= reading.date_observed %></td>
          <td><%= reading.location %></td>
          <td><%= reading.plants_present %></td>
          <td><%= reading.plants_desired %></td>
          <td><%= reading.other_notes %></td>
          <td><%= reading.observed_by %></td>
          <td><%= link_to 'Show', reading %></td>
          <td><%= link_to 'Edit', edit_reading_path(reading) %></td>
          <td><%= link_to 'Delete', reading, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="centre-text">Please add your first reading.</p>
<% end %>
<br>

<%= link_to 'New Reading', new_reading_path %>

app/views/readings/edit.html.erb
<div class="container">

    <h3 class="cfp-pg-header">Editing Reading</h3>

    <%= render 'form', reading: @reading %>

    <%= link_to 'Show', @reading %> |
    <%= link_to 'Back', readings_path %>

</div>

app/views/readings/index.html.erb
<div class="login">

  <% if current_user.is_a?(GuestUser) %>

    <div class="landing-splash">
      <%= link_to root_path do %>
        <%= image_tag("regensoil-logo-1600x1026.png", :alt => "Regensoil QMC Logo", :class => "landing-logo") %>
      <% end %>
    </div>

    <div class="row">
      <div class="col align-self-center landing-title">
        <h2 class="welcome-title">Welcome</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4 landing-instructions-container">
        <h3>Taking a Soil Sample</h3>
        <div class="col align-self-center">
          <h2><%= fa_icon "check-circle-o", class: "text-muted large-icon" %></h2>
        </div>
        <ol>
          <li>Collect 9 soil samples in a Western transect across the field</li>
          <li>Place your samples in a saleable plastic bag</li>
          <li>Label your samples with Field Name, Location, and GPS location</li>
          <li>Take a P.H measurement, penetrometer measurement and any other observations</li>
        </ol>
      </div>

      <div class="col-md-4 landing-instructions-container">
        <h3>Inputting Data</h3>
        <div class="col align-self-center">
          <h2><%= fa_icon "clock-o", class: "text-muted large-icon" %></h2>
        </div>
        <ol>
          <li>For each location you manage, create a new location entry</li>
          <li>Enter the count details and press enter for the next page</li>
          <li>Ensure the QSM assessment is complete within 2 hours</li>
        </ol>
      </div>

      <div class="col-md-4 landing-instructions-container">
        <h3>Your results</h3>
        <div class="col align-self-center">
          <h2><%= fa_icon "bar-chart", class: "text-muted large-icon" %></h2>
        </div>
        <ol>
          <li>Results will be emailed back to you</li>
          <li>All the instructions on how to amend the soil will be included</li>
          <li>Please allow 4 days for the results</li>
        </ol>
      </div>
    </div>

  <% else %>

    <div class="landing-splash">
      <%= link_to root_path do %>
        <%= image_tag("regensoil-logo-800x513.png", :alt => "Regensoil QMC Logo", :class => "logo") %>
      <% end %>
    </div>
    
    <div class="login-inner">
      <%= render 'reading_list', readings: @user_readings %>
    </div>

  <% end %>

</div>

app/views/readings/new.html.erb
<div class="container">

    <h3>New Reading</h3>

    <%= render 'form', reading: @reading %>

    <%= link_to 'Back', readings_path %>

</div>

app/views/readings/readings_page.html.erb
<h1>Readings</h1>

<h2>Options</h2>

    <p><%= link_to "Add", new_page_path %></p>

<% @readings.each do |reading| %>

    <h3><%= reading.land_name %></h3>
    <p><%= reading.crop_growing %></p>
    <p><%= reading.gps %></p>
    <p><%= link_to 'View', page_path(reading) %></p>

<% end %>

app/views/readings/show.html.erb
<div class="container mt-5">

  <p id="notice"><%= notice %></p>

  <h3>Location Details</h3>

    <div class="reading-header-container">
      <table class="reading-header">
        <thead>
          <tr>
            <th>Client</th>
            <th>Organisation</th>
            <th>Date collected</th>
            <th>Date observed</th>
            <th>Location</th>
            <th>Sample Type</th>
            <th>Plants present</th>
            <th>Plants desired</th>
            <th>LT ID</th>
            <th>Customer ID</th>
            <th>Other notes</th>
            <th>Observed by</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
            <tr>
              <td><%= @reading.client %></td>
              <td><%= @reading.organisation %></td>
              <td><%= @reading.date_collected %></td>
              <td><%= @reading.date_observed %></td>
              <td><%= @reading.location %></td>
              <td><%= @reading.sample_type %></td>
              <td><%= @reading.plants_present %></td>
              <td><%= @reading.plants_desired %></td>
              <td><%= @reading.lt_id %></td>
              <td><%= @reading.cust_id %></td>
              <td><%= @reading.other_notes %></td>
              <td><%= @reading.observed_by %></td>
              <td><%= link_to 'Edit', edit_reading_path(@reading) %></td>
              <td><%= link_to 'Back', readings_path  %></td>
            </tr>
        </tbody>
      </table>
    </div>

    <%= render 'sample_report', samples: @samples %>

  <br>

</div>